#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os, time

def touch(filename):
    atime = mtime = time.mktime((2009, 1, 2, 3, 4, 5, 0, 0, -1))
    os.utime(filename, (atime, mtime))

def touch_all_file(dirname):
    for root, dirs, files in os.walk(dirname):
        for f in files:
            filename = os.path.join(root, f)
            touch(filename)
            # print 'touched' + filename

        for d in dirs:
            dirname = os.path.join(root, d)
            touch(dirname)
            # print 'touched' + dirname


touch_all_file(os.getcwd())
print '=========================='
print 'Finalize ... ' + os.getcwd()
print '=========================='
